= Creating MMLC API Documentation

The documentation for the MathML CLoud API is a combination of handwritten explanations, and descriptions generated from an API specification. They are combined and published online by scripted commands.

== Summary

. http://swagger.io/[Swagger] JSON file is written to describe the API
. https://swagger2markup.readme.io/docs[Swagger2Markup] is run to turn the JSON spec into AsciiDoc
. http://asciidoctor.org/[AsciiDoctor] is run to turn AsciiDoc into HTML
. HTML is pushed to https://help.github.com/categories/github-pages-basics/[Github Pages] for public viewing

API Document: http://benetech.github.io/mmlc-api/

== File Layout

Within the `mmlc-api` repository, the documentation source and generated files are under `doc`.
....
doc
	asciidoc
		generated
			overview.adoc
			paths.adoc
			definitions.adoc
		index.adoc
		custom_narrative_a.adoc
		custom_narrative_b.adoc
		path_description_folder
			curl-request.adoc
			http-request.adoc
			http-response.adoc
	json
		mmlc-api.json
....

== Generated Documentation

The source of information for generating documentation segments is a specification of the API written as a Swagger JSON file. It describes the resources provided by the API, the operations allowed on them, and the operations' parameter types and return values. There are lots of tools written around the Swagger spec, both to produce and to consume it; in our case, the JSON is maintained by hand, and we use tools that transform it into other formats.

The Swagger2Markup tool, for example, reads a Swagger JSON file and produces page markup in either AsciiDoc or Markdown format, the default being AsciiDoc. It produces three files, which you then combine with your handwritten files:

. overview.adoc : contains pieces like the base URL and the summary description of the API
. paths.adoc : contains the operations that can be performed on resources
. definitions.adoc : contains the resource descriptions, their properties and their data types

== Written Documentation

In order to guide users in _how_ to use the API, and to describe factors that are universal to the entire API, hand written narratives serve best. For example, descibing how to register to use the API, how to authenticate, or how errors are reported.

These writeups should be in AsciiDoc, in files that can be broken up however we want. The AsciiDoc include mechanism lets us then describe the master document as an ordering of these pages and the generated pages.

For the sample file layout above, the master file, `index.adoc`, might look like this:

....
include::{generated}/overview.adoc
include::custom_narrative_a.adoc
include::custom_narrative_b.adoc
include::{generated}/paths.adoc
include::{generated}/definitions.adoc
....

== Sample Code

Examples of API calls and responses can be included as a mix of written and generated documentation. Swagger2Markup will look for sample files in certain places, and insert them into the generated `paths.adoc` file. The sample files themselves can be hand written or generated by some other tool, so long as they end up in the right place.

Swagger2Markup uses the "summmary" string for a Swagger path element when looking for sample code. It lower cases the string and replaces spaces with underscores, then looks for a folder with that name. For example, a path summarized as "Get HTML5 Equation" becomes "get_html5_equation". Within that folder, it will make use of three files, if they exist:

. curl-request.adoc : An example cURL comand line call
. http-request.adoc : What HTTP request headers should look like, for those not using cURL
. http-response.adoc : What HTTP response headers and body would look like

== Modifying Layout Style

The default stylesheet of AsciiDoctor provides a simple, clean look and basic layout options like a sidebar table of contents are command line options. There are many options for including alternative style sheets, producing other formats (PDF, EPUB 3, etc), and generating additional document additions.

== Publishing

Once the Swagger JSON is created and other documentation and examples are written, the pieces are combined and transformed into HTML, and then published.

=== Install tools

. https://swagger2markup.readme.io/docs/cli[Swagger2Markup CLI], requires Java 7
. http://asciidoctor.org/docs/install-toolchain/[AsciiDoctor], requires Ruby 1.9+

=== Checkout Current Documentation

Make a separate clone of the mmlc-api repository, and switch to the `gh-pages` branch.
....
cd ~/code
git clone https://github.com/benetech/mmlc-api.git mmlc-api-docs
cd mmlc-api-docs
git checkout gh-pages
....

From the main mmlc-api repository, generate the HTML
....
cd ~/code/mmlc-api
java -jar ~/tools/swagger2markup-cli/build/libs/swagger2markup-cli-0.9.1.jar \
	generate -i doc/json/mmlc-api.json -o doc/asciidoc/generated/ \
	-l ASCIIDOC -g TAGS -n NATURAL -e doc/asciidoc/
asciidoctor doc/asciidoc/index.adoc \
	-a generated=generated -a toc=left -a toclevels=3
....

Open the file `doc/asciidoc/index.html` in a browser and review the results.

=== Commit Changes

....
cp doc/asciidoc/index.html ~/tools/mmlc-api-doc
cd ~/tools/mmlc-api-doc
git push origin gh-pages
....

== Tool Documentation

. https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md[Swagger Specification]
. https://swagger2markup.readme.io/docs/usage-guide[Swagger2Markup Usage Guide]
. http://asciidoctor.org/docs/asciidoc-syntax-quick-reference/[AsciiDoctor Reference]
. https://help.github.com/articles/creating-project-pages-manually/[Github Pages]
